name: Commit Tests

on: [pull_request]

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Commit Linter
      uses: wagoid/commitlint-github-action@v2.0.3
