name: Syntax Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: psf/black@stable
      with:
        args: -S --check --diff .
    - name: Syntax check
      run: |
        flake8 .
